name: Check tests

on:
  push:
    branches: 
      - main

  pull_request:
    branches: 
      - main
      - develop
    
  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: Check Linter 📑
        run: |
          npm install
          npx eslint . --ext .js,.jsx,.ts,.tsx

  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Prepare Tests
        working-directory: './packages/millicast-sdk'
        run: echo -n ${{secrets.MILLICAST_TEST_ACCOUNT}} | base64 -d > ./tests/test-env.js

      - name: Test 🧪
        working-directory: './packages/millicast-sdk'
        run: |
          npm install
          npm test
  
      - name: Test End-2-End
        uses: tj-actions/puppeteer@v3.2
        with:
          args: npm run test-e2e